### ISSUE TITLE
Loops back into login screen

### ISSUE THREAD

**Issue by metallicats** [mangospot-net/MangoRad#1]
As suggested, I managed to enable **.htaccess** and checked **php-mcrypt** (already installed). Now I was able to see the login screen.
Used **admin** as username and password but it loops back into the login page.

Also checked apache2 error.log but there were no errors there.

Anything I missed?

**Comment by doko89** [comment]
Me too

loop di halaman login mas? ada yg salah kah?

**Comment by Focuslinkstech** [comment]
Same here, It lopped back to the login page did anyone find solution to this issue?
